import './components/text-input/base-input';
import './components/text-input/text-box';
import './components/text-input/phone-box';
import './components/text-input/email-box';
import './components/text-input/plate-box';
import './components/text-input/integer-box';
import './components/url-link';
import './components/check-box';
import './components/select-box';
