import TextBox from './components/text-input/text-box';
import PhoneBox from './components/text-input/phone-box';
import EmailBox from './components/text-input/email-box';
import PlateBox from './components/text-input/plate-box.js';
import IntegerBox from './components/text-input/integer-box';
import NewPasswordBox from './components/text-input/new-password-box';
import PasswordBox from './components/text-input/password-box';
import ConfirmPasswordBox from './components/text-input/confirm-password-box';
import UrlLink from './components/button/url-link';
import CheckBox from './components/select/check-box';
import SelectBox from './components/select/select-box';
import ComboBox from './components/select/combo-box';
import RangeSelect from './components/select/range-select';
import ModalDialog from './components/dialog/modal-dialog';
import { defineComponent } from './modules/utilities.js';
import TcBox from './components/text-input/tc-box.js';
import TableComponent from './components/table/table.js';
import Pagination from './components/table/pagination.js';

defineComponent('typed-table', TableComponent);
defineComponent('typed-pagination', Pagination);

defineComponent('text-box', TextBox);
defineComponent('phone-box', PhoneBox);
defineComponent('email-box', EmailBox);
defineComponent('plate-box', PlateBox);
defineComponent('integer-box', IntegerBox);
defineComponent('new-password-box', NewPasswordBox);
defineComponent('password-box', PasswordBox);
defineComponent('confirm-password-box', ConfirmPasswordBox);
defineComponent('url-link', UrlLink);
defineComponent('check-box', CheckBox);
defineComponent('select-box', SelectBox);
defineComponent('combo-box', ComboBox);
defineComponent('range-select', RangeSelect);
defineComponent('modal-dialog', ModalDialog);
defineComponent('tc-box', TcBox);
